# Sway titlebar animation. Works best in tabbed/stacked layouts, but applies to
# regular titlebars too.
title_align left
titlebar_border_thickness 1
titlebar_padding 8 3
show_marks yes
exec_always --no-startup-id sway-title-animator --replace --preset showcase --fps 25
